[package]
name = "rustglue"
version = "0.1.0"
authors = ["Henri Sivonen <hsivonen@hsivonen.fi>"]

[dependencies.encoding_c]
version = "0.9.5"

[lib]
crate-type = ["staticlib"]

[profile.release]
lto = true
panic = 'abort'

[profile.dev]
panic = 'abort'
